"""Added clients And relations

Revision ID: 1d52089deb4c
Revises: e2412789c190
Create Date: 2024-04-23 08:56:01.679585

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1d52089deb4c'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instagram', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('openForConnections', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False, comment='0 - open, 1 - closed'),
    sa.Column('priority', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False, comment='0 - no priority, 1 - priority'),
    sa.Column('isReached', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False, comment='0 - no, 1 - yes'),
    sa.Column('status', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False, comment='0 - inactive, 1 - active'),
    sa.PrimaryKeyConstraint('id', name='clients_pkey')
    )
    op.create_table('relations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fromClientId', sa.INTEGER(), autoincrement=False, nullable=False, comment='relation from'),
    sa.Column('toClientId', sa.INTEGER(), autoincrement=False, nullable=False, comment='relation to'),
    sa.Column('status', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False, comment='0 - inactive, 1 - active'),
    sa.PrimaryKeyConstraint('id', name='relations_pkey')
    )
    # ### end Alembic commands ###
